import { GetLatestInterviewsParams} from "@/src/types";
import { Interview } from "@/src/types";
import Interviews from "../models/Interviews";
import dbConnect from "./dbConnect";
import { CreateFeedbackParams } from "@/src/types";
import { generateObject } from "ai";
import { feedbackSchema } from "../constants";
import { google } from "@ai-sdk/google";





//function for getting the generated interviews from db in descending order
export  async function getInterviewByUserId(userId:string):Promise<Interview[] | null>{
    await dbConnect();

    const interviews = await Interviews.find({userId}).sort({createdAt:-1});

    return interviews;
}




//function for getting the interviews generated by other users
export async function getLatestInterviews(params : GetLatestInterviewsParams):Promise<Interview[] | null>{
     await dbConnect();
    const{userId , limit=20}=params;
    const interviews=await Interviews.find({
        finalized:true ,
        userId: {$ne : userId}

    }).sort({createdAt:-1})
    .limit(limit);
    return interviews;
}


//here we will get the interview by interview id
export async function getInterviewById(id:string): Promise<Interview>{
await dbConnect();
 const interview = await Interviews.findById(id);
 return interview;
}

export async function createFeedBack(params : CreateFeedbackParams){
    const {interviewId , userId , transcript}=params;

    try{

        const formattedTranscript= transcript.map((sentence:{role:string ; content:string})=>(
                    `-${sentence.role}: ${sentence.content}\n` // ai -> question , me ->answer
        )).join(" ");


        const {object:{totalScore , categoryScores , strengths , areasForImprovement , finalAssessment}}= await generateObject({
     model: google("gemini-2.0-flash-001"),
      schema: feedbackSchema,
      prompt: `
        You are an AI interviewer analyzing a mock interview. Your task is to evaluate the candidate based on structured categories. Be thorough and detailed in your analysis. Don't be lenient with the candidate. If there are mistakes or areas for improvement, point them out.
        Transcript:
        ${formattedTranscript}

        Please score the candidate from 0 to 100 in the following areas. Do not add categories other than the ones provided:
        - **Communication Skills**: Clarity, articulation, structured responses.
        - **Technical Knowledge**: Understanding of key concepts for the role.
        - **Problem-Solving**: Ability to analyze problems and propose solutions.
        - **Cultural & Role Fit**: Alignment with company values and job role.
        - **Confidence & Clarity**: Confidence in responses, engagement, and clarity.
        `,
      system:
        "You are a professional interviewer analyzing a mock interview. Your task is to evaluate the candidate based on structured categories",
    });

    }catch(e){
        console.log("Error displaying feedback" , e);
    }

}